### ISSUE TITLE
Allow Catniss to "stalk" other players (if a match isn't found)

### ISSUE THREAD

**Issue by nstringham** [cat-acronym-team/cat-me-if-you-can#34]
If there is an odd number of players and Catniss cannot find a match that round, she should be able to select a matching pair to view their entire chat log during the chatting phase. so that she doesn't feel left out that round.

**Tasks:**

- [x] Assign random player as stalker after checking odd # of players in Backend
- [x] Display chats as buttons with who is talking with who in Frontend
- [x] Chat buttons should be clickable which will take user to selected chat in Backend
- [x] Stalker should be taken to stalker component in Backend.
- [x] Stalker should join a chat anonymously with read-only function Backend.

**Acceptance Criteria**

- If there is an even number of players in the lobby, this pseudo-role does not exist until there is an odd number.
- If there is an odd number of players, one player selected at random will become a stalker
- If the user is the stalker, they should be shown the current pairs in the round to which they can select which pair they want to stalk
- When stalking, they should be able to see the current chatting between the selected pair
- If the user is not the stalker, they would play the chatting phase normally
- If the user is being stalked, they should not be able to see that they are being stalked until the voting phase
- A hacker shouldn't be able to see if they are being stalked
- A hacker who is the stalker should not be able to stock more than one pair
- A hacker w should not be able to influence who is the stalker

**Comment by njumaah** [comment]
criteria: A hacker shouldn't be able to see if they are being stalked is the only thing left to do

**Comment by njumaah** [comment]
take stalker out of viewers list. try putting chatid inside the private players
