### ISSUE TITLE
Allow Catniss to select a avatar

### ISSUE THREAD

**Issue by nstringham** [cat-acronym-team/cat-me-if-you-can#35]
Catniss will be able to select which avatar they wish to play as on the create lobby page because pictures are easier to remember than words and because cat pictures are adorable and Catniss wants to be able to choose the cutest one.

**Tasks:**

- [x] Buttons for each avatar option for Frontend
- [x] Backend should assign Catniss to avatar
- [x] make front end look good

Acceptance Criteria
- The user should be able to select the cat avatar they will be playing with during the game
- Only one player should be allowed to be each cat avatar
- User is assigned a random available avatar when the join

**Comment by njumaah** [comment]
Need create lobby page done before we can work on this.
