### ISSUE TITLE
Allow Catniss to view the game rules

### ISSUE THREAD

**Issue by nstringham** [cat-acronym-team/cat-me-if-you-can#44]
Catniss should be able to click on the question mark on any of the pages and be show the rules page where there is a list of rules to play the game so that she is able to learn the basics of the game without having to ask others in the lobby.

**Tasks:**

- [x] Inquire team about game rules.
- [x] Format UI in Frontend.
- [x] Fill in rules.

Acceptance Criteria:
- Catniss should be able to view rules in a modal
- UI should be formatted appropriately
- Game rules should be decided on by the entire team
