### ISSUE TITLE
Allow Catniss to remove others from lobby (if she is host)

### ISSUE THREAD

**Issue by nstringham** [cat-acronym-team/cat-me-if-you-can#45]
There will be a kick and ban button; users that are banned can no longer join with the link. This is to prevent unwanted people who somehow obtain the lobby code/link from joining and taking up a spot in the lobby. Kicking should serve as a temporary removal in case it is not a serious offense.

**Tasks:**

- [x] Does not allow banned players to join in any form via a check in Backend.
- [x] Display dropdown onClick in Frontend.
- [x] Display kick button in Frontend.
- [x] Display ban button in Frontend.
- [x] Assign kick power to host in Backend and server to ensure only the host may do this.
- [x] Assign ban power to host in Backend and server to ensure only the host may do this.

**Acceptance Criteria:**
- Catniss can click kick button on drop-down to kick player from lobby (is temporary removal)
- Catniss can click ban button on drop-down to ban player from lobby (permanent removal)
- Doesn't allow users to join back through code or link if banned
- Only the host can kick or ban players from lobby
- A hacker that was banned should not be able to join a game they were banned from
- A hacker should not be able to ban/kick users if they are not the host
- If a player is kicked or banded they should be taken to the join page
